--------------------------------------------------------------------------------
-- OCI AGENTIC AWR DEMO
-- TOPOLOGY / PLATFORM UPGRADE DDL v3 - SAFE INCREMENTAL VERSION
-- Applies on top of existing working schema. Does NOT recreate schema.
--------------------------------------------------------------------------------

SPOOL ddlv3-1_topology_platform_safe.log
SET SQLBLANKLINES ON
SET DEFINE OFF
SET ECHO ON
SET TIMING ON
SET SERVEROUTPUT ON

--------------------------------------------------------------------------------
-- 1. ADD NEW COLUMNS SAFELY
--------------------------------------------------------------------------------

BEGIN
  BEGIN
    EXECUTE IMMEDIATE '
      ALTER TABLE AWR_SOURCE_SYSTEM ADD (
        DATABASE_ROLE VARCHAR2(64),
        INSTANCE_COUNT NUMBER
      )';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE = -1430 THEN NULL; ELSE RAISE; END IF;
  END;
END;
/
SHOW ERRORS

BEGIN
  BEGIN
    EXECUTE IMMEDIATE '
      ALTER TABLE AWR_FEATURE_VECTOR ADD (
        TOPOLOGY_CLASS VARCHAR2(64),
        PLATFORM_CLASS VARCHAR2(64),
        EVENT_CLASS VARCHAR2(64)
      )';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE = -1430 THEN NULL; ELSE RAISE; END IF;
  END;
END;
/
SHOW ERRORS

BEGIN
  BEGIN
    EXECUTE IMMEDIATE '
      ALTER TABLE AWR_SCORE_RESULT ADD (
        WORKLOAD_CLASS VARCHAR2(64),
        TOPOLOGY_CLASS VARCHAR2(64),
        PLATFORM_CLASS VARCHAR2(64),
        EVENT_CLASS VARCHAR2(64),
        PRIMARY_SIGNAL_DOMAIN VARCHAR2(64)
      )';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE = -1430 THEN NULL; ELSE RAISE; END IF;
  END;
END;
/
SHOW ERRORS

--------------------------------------------------------------------------------
-- 2. BACKFILL NEW CLASSIFICATION COLUMNS FROM EXISTING JSON PAYLOADS
--    Safe for current rows already stored by the updated Python code.
--------------------------------------------------------------------------------

UPDATE AWR_FEATURE_VECTOR fv
   SET TOPOLOGY_CLASS = JSON_VALUE(fv.FEATURE_JSON, '$.TOPOLOGY_CLASS' RETURNING VARCHAR2(64) NULL ON ERROR),
       PLATFORM_CLASS = JSON_VALUE(fv.FEATURE_JSON, '$.PLATFORM_CLASS' RETURNING VARCHAR2(64) NULL ON ERROR),
       EVENT_CLASS    = JSON_VALUE(fv.FEATURE_JSON, '$.OPERATIONAL_EVENT_CLASS' RETURNING VARCHAR2(64) NULL ON ERROR)
 WHERE (fv.TOPOLOGY_CLASS IS NULL OR fv.PLATFORM_CLASS IS NULL OR fv.EVENT_CLASS IS NULL)
   AND fv.FEATURE_JSON IS NOT NULL;

UPDATE AWR_SCORE_RESULT sr
   SET WORKLOAD_CLASS = JSON_VALUE(sr.SCORECARD_JSON, '$.workload_class' RETURNING VARCHAR2(64) NULL ON ERROR),
       TOPOLOGY_CLASS = JSON_VALUE(sr.SCORECARD_JSON, '$.topology_class' RETURNING VARCHAR2(64) NULL ON ERROR),
       PLATFORM_CLASS = JSON_VALUE(sr.SCORECARD_JSON, '$.platform_class' RETURNING VARCHAR2(64) NULL ON ERROR),
       EVENT_CLASS = JSON_VALUE(sr.SCORECARD_JSON, '$.event_class' RETURNING VARCHAR2(64) NULL ON ERROR),
       PRIMARY_SIGNAL_DOMAIN = JSON_VALUE(sr.SCORECARD_JSON, '$.primary_signal_domain' RETURNING VARCHAR2(64) NULL ON ERROR)
 WHERE (sr.WORKLOAD_CLASS IS NULL
    OR sr.TOPOLOGY_CLASS IS NULL
    OR sr.PLATFORM_CLASS IS NULL
    OR sr.EVENT_CLASS IS NULL
    OR sr.PRIMARY_SIGNAL_DOMAIN IS NULL)
   AND sr.SCORECARD_JSON IS NOT NULL;

UPDATE AWR_SOURCE_SYSTEM s
   SET DATABASE_ROLE = (
         SELECT MAX(JSON_VALUE(fv.FEATURE_JSON, '$.DATABASE_ROLE' RETURNING VARCHAR2(64) NULL ON ERROR))
           FROM AWR_FEATURE_VECTOR fv
          WHERE fv.SOURCE_SYSTEM_ID = s.SOURCE_SYSTEM_ID
       ),
       INSTANCE_COUNT = (
         SELECT MAX(
                  TO_NUMBER(
                    JSON_VALUE(fv.FEATURE_JSON, '$.INSTANCE_COUNT' RETURNING VARCHAR2(64) NULL ON ERROR)
                  )
                )
           FROM AWR_FEATURE_VECTOR fv
          WHERE fv.SOURCE_SYSTEM_ID = s.SOURCE_SYSTEM_ID
       )
 WHERE EXISTS (
         SELECT 1
           FROM AWR_FEATURE_VECTOR fv
          WHERE fv.SOURCE_SYSTEM_ID = s.SOURCE_SYSTEM_ID
       );

COMMIT;

--------------------------------------------------------------------------------
-- 3. CREATE SAFE NON-PARTITIONED INDEXES
--    Do NOT use LOCAL here unless your tables are truly partitioned.
--------------------------------------------------------------------------------

BEGIN
  BEGIN
    EXECUTE IMMEDIATE '
      CREATE INDEX IX_AWR_FEATURE_VECTOR_02
          ON AWR_FEATURE_VECTOR (TOPOLOGY_CLASS, PLATFORM_CLASS, EVENT_CLASS, AWR_ID)';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
  END;
END;
/
SHOW ERRORS

BEGIN
  BEGIN
    EXECUTE IMMEDIATE '
      CREATE INDEX IX_AWR_SCORE_RESULT_04
          ON AWR_SCORE_RESULT (TOPOLOGY_CLASS, PLATFORM_CLASS, EVENT_CLASS, AWR_ID)';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
  END;
END;
/
SHOW ERRORS

--------------------------------------------------------------------------------
-- 4. OPTIONAL JSON FUNCTION-BASED INDEXES
--    Safe and useful, but not required for correctness.
--------------------------------------------------------------------------------

BEGIN
  BEGIN
    EXECUTE IMMEDIATE '
      CREATE INDEX IX_AWR_FEATURE_VECTOR_JSON_02
          ON AWR_FEATURE_VECTOR (
            JSON_VALUE(FEATURE_JSON, ''$.TOPOLOGY_CLASS'' RETURNING VARCHAR2(64) NULL ON ERROR),
            JSON_VALUE(FEATURE_JSON, ''$.PLATFORM_CLASS'' RETURNING VARCHAR2(64) NULL ON ERROR),
            JSON_VALUE(FEATURE_JSON, ''$.OPERATIONAL_EVENT_CLASS'' RETURNING VARCHAR2(64) NULL ON ERROR)
          )';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
  END;
END;
/
SHOW ERRORS

BEGIN
  BEGIN
    EXECUTE IMMEDIATE '
      CREATE INDEX IX_AWR_SCORE_RESULT_JSON_02
          ON AWR_SCORE_RESULT (
            JSON_VALUE(SCORECARD_JSON, ''$.topology_class'' RETURNING VARCHAR2(64) NULL ON ERROR),
            JSON_VALUE(SCORECARD_JSON, ''$.platform_class'' RETURNING VARCHAR2(64) NULL ON ERROR),
            JSON_VALUE(SCORECARD_JSON, ''$.event_class'' RETURNING VARCHAR2(64) NULL ON ERROR)
          )';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
  END;
END;
/
SHOW ERRORS

--------------------------------------------------------------------------------
-- 5. SEED TOPOLOGY / PLATFORM WEIGHTS INTO EXISTING MODEL
--------------------------------------------------------------------------------

INSERT INTO AWR_SCORING_WEIGHT (
    SCORING_MODEL_ID, FEATURE_CODE, FEATURE_NAME, FEATURE_DOMAIN, FEATURE_PATH,
    WEIGHT_VALUE, NORMALIZATION_METHOD, TRANSFORM_METHOD, POLARITY, NOTES
)
SELECT
    m.SCORING_MODEL_ID,
    'CLUSTER_WAIT_PCT_DB_TIME',
    'Cluster Wait Pressure',
    'CLUSTER',
    '$.CLUSTER_WAIT_PCT_DB_TIME',
    0.14,
    'MINMAX',
    'NONE',
    'HIGH_BAD',
    'Topology-aware RAC scoring weight'
FROM AWR_SCORING_MODEL m
WHERE m.MODEL_CODE = 'AWR_WEIGHTED_CORE'
  AND NOT EXISTS (
      SELECT 1
      FROM AWR_SCORING_WEIGHT w
      WHERE w.SCORING_MODEL_ID = m.SCORING_MODEL_ID
        AND w.FEATURE_CODE = 'CLUSTER_WAIT_PCT_DB_TIME'
  );

INSERT INTO AWR_SCORING_WEIGHT (
    SCORING_MODEL_ID, FEATURE_CODE, FEATURE_NAME, FEATURE_DOMAIN, FEATURE_PATH,
    WEIGHT_VALUE, NORMALIZATION_METHOD, TRANSFORM_METHOD, POLARITY, NOTES
)
SELECT
    m.SCORING_MODEL_ID,
    'GC_CURRENT_WAIT_PCT_DB_TIME',
    'GC Current Wait Pressure',
    'CLUSTER',
    '$.GC_CURRENT_WAIT_PCT_DB_TIME',
    0.10,
    'MINMAX',
    'NONE',
    'HIGH_BAD',
    'Topology-aware RAC current block wait scoring weight'
FROM AWR_SCORING_MODEL m
WHERE m.MODEL_CODE = 'AWR_WEIGHTED_CORE'
  AND NOT EXISTS (
      SELECT 1
      FROM AWR_SCORING_WEIGHT w
      WHERE w.SCORING_MODEL_ID = m.SCORING_MODEL_ID
        AND w.FEATURE_CODE = 'GC_CURRENT_WAIT_PCT_DB_TIME'
  );

INSERT INTO AWR_SCORING_WEIGHT (
    SCORING_MODEL_ID, FEATURE_CODE, FEATURE_NAME, FEATURE_DOMAIN, FEATURE_PATH,
    WEIGHT_VALUE, NORMALIZATION_METHOD, TRANSFORM_METHOD, POLARITY, NOTES
)
SELECT
    m.SCORING_MODEL_ID,
    'TRANSPORT_LAG_SEC',
    'Transport Lag',
    'DG',
    '$.TRANSPORT_LAG_SEC',
    0.12,
    'MINMAX',
    'LOG1P',
    'HIGH_BAD',
    'Topology-aware Data Guard transport lag scoring weight'
FROM AWR_SCORING_MODEL m
WHERE m.MODEL_CODE = 'AWR_WEIGHTED_CORE'
  AND NOT EXISTS (
      SELECT 1
      FROM AWR_SCORING_WEIGHT w
      WHERE w.SCORING_MODEL_ID = m.SCORING_MODEL_ID
        AND w.FEATURE_CODE = 'TRANSPORT_LAG_SEC'
  );

INSERT INTO AWR_SCORING_WEIGHT (
    SCORING_MODEL_ID, FEATURE_CODE, FEATURE_NAME, FEATURE_DOMAIN, FEATURE_PATH,
    WEIGHT_VALUE, NORMALIZATION_METHOD, TRANSFORM_METHOD, POLARITY, NOTES
)
SELECT
    m.SCORING_MODEL_ID,
    'APPLY_LAG_SEC',
    'Apply Lag',
    'DG',
    '$.APPLY_LAG_SEC',
    0.12,
    'MINMAX',
    'LOG1P',
    'HIGH_BAD',
    'Topology-aware Data Guard apply lag scoring weight'
FROM AWR_SCORING_MODEL m
WHERE m.MODEL_CODE = 'AWR_WEIGHTED_CORE'
  AND NOT EXISTS (
      SELECT 1
      FROM AWR_SCORING_WEIGHT w
      WHERE w.SCORING_MODEL_ID = m.SCORING_MODEL_ID
        AND w.FEATURE_CODE = 'APPLY_LAG_SEC'
  );

INSERT INTO AWR_SCORING_WEIGHT (
    SCORING_MODEL_ID, FEATURE_CODE, FEATURE_NAME, FEATURE_DOMAIN, FEATURE_PATH,
    WEIGHT_VALUE, NORMALIZATION_METHOD, TRANSFORM_METHOD, POLARITY, NOTES
)
SELECT
    m.SCORING_MODEL_ID,
    'FAILOVER_EVENT_FLAG',
    'Failover Event',
    'TOPOLOGY_EVENT',
    '$.FAILOVER_EVENT_FLAG',
    0.18,
    'MINMAX',
    'NONE',
    'HIGH_BAD',
    'Operational transition scoring weight'
FROM AWR_SCORING_MODEL m
WHERE m.MODEL_CODE = 'AWR_WEIGHTED_CORE'
  AND NOT EXISTS (
      SELECT 1
      FROM AWR_SCORING_WEIGHT w
      WHERE w.SCORING_MODEL_ID = m.SCORING_MODEL_ID
        AND w.FEATURE_CODE = 'FAILOVER_EVENT_FLAG'
  );

INSERT INTO AWR_SCORING_WEIGHT (
    SCORING_MODEL_ID, FEATURE_CODE, FEATURE_NAME, FEATURE_DOMAIN, FEATURE_PATH,
    WEIGHT_VALUE, NORMALIZATION_METHOD, TRANSFORM_METHOD, POLARITY, NOTES
)
SELECT
    m.SCORING_MODEL_ID,
    'ROLE_TRANSITION_FLAG',
    'Role Transition Event',
    'TOPOLOGY_EVENT',
    '$.ROLE_TRANSITION_FLAG',
    0.12,
    'MINMAX',
    'NONE',
    'HIGH_BAD',
    'Operational role-transition scoring weight'
FROM AWR_SCORING_MODEL m
WHERE m.MODEL_CODE = 'AWR_WEIGHTED_CORE'
  AND NOT EXISTS (
      SELECT 1
      FROM AWR_SCORING_WEIGHT w
      WHERE w.SCORING_MODEL_ID = m.SCORING_MODEL_ID
        AND w.FEATURE_CODE = 'ROLE_TRANSITION_FLAG'
  );

INSERT INTO AWR_SCORING_WEIGHT (
    SCORING_MODEL_ID, FEATURE_CODE, FEATURE_NAME, FEATURE_DOMAIN, FEATURE_PATH,
    WEIGHT_VALUE, NORMALIZATION_METHOD, TRANSFORM_METHOD, POLARITY, NOTES
)
SELECT
    m.SCORING_MODEL_ID,
    'POST_FAILOVER_RECOVERY_FLAG',
    'Post-Failover Recovery',
    'TOPOLOGY_EVENT',
    '$.POST_FAILOVER_RECOVERY_FLAG',
    0.12,
    'MINMAX',
    'NONE',
    'HIGH_BAD',
    'Operational recovery scoring weight'
FROM AWR_SCORING_MODEL m
WHERE m.MODEL_CODE = 'AWR_WEIGHTED_CORE'
  AND NOT EXISTS (
      SELECT 1
      FROM AWR_SCORING_WEIGHT w
      WHERE w.SCORING_MODEL_ID = m.SCORING_MODEL_ID
        AND w.FEATURE_CODE = 'POST_FAILOVER_RECOVERY_FLAG'
  );

INSERT INTO AWR_SCORING_WEIGHT (
    SCORING_MODEL_ID, FEATURE_CODE, FEATURE_NAME, FEATURE_DOMAIN, FEATURE_PATH,
    WEIGHT_VALUE, NORMALIZATION_METHOD, TRANSFORM_METHOD, POLARITY, NOTES
)
SELECT
    m.SCORING_MODEL_ID,
    'EXA_CELL_IO_PCT_DB_TIME',
    'Exadata Cell Wait Pressure',
    'EXADATA',
    '$.EXA_CELL_IO_PCT_DB_TIME',
    0.10,
    'MINMAX',
    'NONE',
    'HIGH_BAD',
    'Engineered-system wait pressure weight'
FROM AWR_SCORING_MODEL m
WHERE m.MODEL_CODE = 'AWR_WEIGHTED_CORE'
  AND NOT EXISTS (
      SELECT 1
      FROM AWR_SCORING_WEIGHT w
      WHERE w.SCORING_MODEL_ID = m.SCORING_MODEL_ID
        AND w.FEATURE_CODE = 'EXA_CELL_IO_PCT_DB_TIME'
  );

INSERT INTO AWR_SCORING_WEIGHT (
    SCORING_MODEL_ID, FEATURE_CODE, FEATURE_NAME, FEATURE_DOMAIN, FEATURE_PATH,
    WEIGHT_VALUE, NORMALIZATION_METHOD, TRANSFORM_METHOD, POLARITY, NOTES
)
SELECT
    m.SCORING_MODEL_ID,
    'EXA_OFFLOAD_EFFICIENCY',
    'Exadata Offload Efficiency',
    'EXADATA',
    '$.EXA_OFFLOAD_EFFICIENCY',
    0.08,
    'MINMAX',
    'NONE',
    'HIGH_GOOD',
    'Beneficial engineered-system offload weight'
FROM AWR_SCORING_MODEL m
WHERE m.MODEL_CODE = 'AWR_WEIGHTED_CORE'
  AND NOT EXISTS (
      SELECT 1
      FROM AWR_SCORING_WEIGHT w
      WHERE w.SCORING_MODEL_ID = m.SCORING_MODEL_ID
        AND w.FEATURE_CODE = 'EXA_OFFLOAD_EFFICIENCY'
  );

INSERT INTO AWR_SCORING_WEIGHT (
    SCORING_MODEL_ID, FEATURE_CODE, FEATURE_NAME, FEATURE_DOMAIN, FEATURE_PATH,
    WEIGHT_VALUE, NORMALIZATION_METHOD, TRANSFORM_METHOD, POLARITY, NOTES
)
SELECT
    m.SCORING_MODEL_ID,
    'SMART_SCAN_FLAG',
    'Smart Scan Active',
    'EXADATA',
    '$.SMART_SCAN_FLAG',
    0.06,
    'MINMAX',
    'NONE',
    'HIGH_GOOD',
    'Beneficial smart scan scoring weight'
FROM AWR_SCORING_MODEL m
WHERE m.MODEL_CODE = 'AWR_WEIGHTED_CORE'
  AND NOT EXISTS (
      SELECT 1
      FROM AWR_SCORING_WEIGHT w
      WHERE w.SCORING_MODEL_ID = m.SCORING_MODEL_ID
        AND w.FEATURE_CODE = 'SMART_SCAN_FLAG'
  );

COMMIT;

--------------------------------------------------------------------------------
-- 6. QUICK VALIDATION
--------------------------------------------------------------------------------

PROMPT
PROMPT =============================
PROMPT V3 UPGRADE VALIDATION
PROMPT =============================

SELECT column_name
FROM user_tab_cols
WHERE table_name = 'AWR_SOURCE_SYSTEM'
  AND column_name IN ('DATABASE_ROLE', 'INSTANCE_COUNT')
ORDER BY column_name;

SELECT column_name
FROM user_tab_cols
WHERE table_name = 'AWR_FEATURE_VECTOR'
  AND column_name IN ('TOPOLOGY_CLASS', 'PLATFORM_CLASS', 'EVENT_CLASS')
ORDER BY column_name;

SELECT column_name
FROM user_tab_cols
WHERE table_name = 'AWR_SCORE_RESULT'
  AND column_name IN ('WORKLOAD_CLASS', 'TOPOLOGY_CLASS', 'PLATFORM_CLASS', 'EVENT_CLASS', 'PRIMARY_SIGNAL_DOMAIN')
ORDER BY column_name;

SELECT feature_code, feature_domain, weight_value
FROM awr_scoring_weight
WHERE feature_code IN (
  'CLUSTER_WAIT_PCT_DB_TIME',
  'GC_CURRENT_WAIT_PCT_DB_TIME',
  'TRANSPORT_LAG_SEC',
  'APPLY_LAG_SEC',
  'FAILOVER_EVENT_FLAG',
  'ROLE_TRANSITION_FLAG',
  'POST_FAILOVER_RECOVERY_FLAG',
  'EXA_CELL_IO_PCT_DB_TIME',
  'EXA_OFFLOAD_EFFICIENCY',
  'SMART_SCAN_FLAG'
)
ORDER BY feature_code;

SPOOL OFF
