i--------------------------------------------------------------------------------
-- OCI AGENTIC AWR DEMO
-- FULL PRODUCTION-STYLE ADB DDL v2
-- Target: Oracle Autonomous Database / Oracle AI Database
--
-- Design goals:
--   * Multi-AWR ingestion
--   * Replay/testing ingestion of same AWR file
--   * Native JSON storage for parsed/raw payloads
--   * Partitioned fact/history tables
--   * Top SQL trending
--   * Wait event / wait class trending
--   * Feature vectors + semantic embeddings
--   * Scoring / weighting / recommendation / action / feedback loop
--   * ML-ready outcome capture
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- 0. CLEANUP (OPTIONAL)
--------------------------------------------------------------------------------
DROP VIEW  VW_AWR_REPORT_LATEST;
DROP VIEW  VW_AWR_RECOMMENDATION_CYCLE;
DROP VIEW  VW_AWR_TOP_SQL_TREND;
DROP VIEW  VW_AWR_WAIT_EVENT_TREND;

DROP TABLE AWR_MODEL_RUN             CASCADE CONSTRAINTS PURGE;
DROP TABLE AWR_OUTCOME               CASCADE CONSTRAINTS PURGE;
DROP TABLE AWR_ACTION                CASCADE CONSTRAINTS PURGE;
DROP TABLE AWR_RECOMMENDATION        CASCADE CONSTRAINTS PURGE;
DROP TABLE AWR_SCORE_RESULT          CASCADE CONSTRAINTS PURGE;
DROP TABLE AWR_SCORING_WEIGHT        CASCADE CONSTRAINTS PURGE;
DROP TABLE AWR_SCORING_MODEL         CASCADE CONSTRAINTS PURGE;
DROP TABLE AWR_FEATURE_VECTOR        CASCADE CONSTRAINTS PURGE;
DROP TABLE AWR_WAIT_EVENT_FACT       CASCADE CONSTRAINTS PURGE;
DROP TABLE AWR_TOP_SQL_FACT          CASCADE CONSTRAINTS PURGE;
DROP TABLE AWR_METRIC_FACT           CASCADE CONSTRAINTS PURGE;
DROP TABLE AWR_SECTION_DOC           CASCADE CONSTRAINTS PURGE;
DROP TABLE AWR_REPORT                CASCADE CONSTRAINTS PURGE;
DROP TABLE AWR_INGEST_RUN            CASCADE CONSTRAINTS PURGE;
DROP TABLE AWR_SOURCE_SYSTEM         CASCADE CONSTRAINTS PURGE;

--------------------------------------------------------------------------------
-- 1. SOURCE SYSTEM / DATABASE REGISTRY
--------------------------------------------------------------------------------
CREATE TABLE AWR_SOURCE_SYSTEM (
    SOURCE_SYSTEM_ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SOURCE_SYSTEM_CODE       VARCHAR2(100)       NOT NULL,
    TENANCY_NAME             VARCHAR2(256),
    COMPARTMENT_NAME         VARCHAR2(256),
    ENVIRONMENT_NAME         VARCHAR2(100),
    CUSTOMER_NAME            VARCHAR2(256),
    APPLICATION_NAME         VARCHAR2(256),

    DB_NAME                  VARCHAR2(128),
    DB_UNIQUE_NAME           VARCHAR2(128),
    DBID                     NUMBER,
    PLATFORM_NAME            VARCHAR2(256),
    DB_VERSION               VARCHAR2(64),
    RAC_FLAG                 CHAR(1) DEFAULT 'N' CHECK (RAC_FLAG IN ('Y','N')),
    ADG_FLAG                 CHAR(1) DEFAULT 'N' CHECK (ADG_FLAG IN ('Y','N')),
    CDB_FLAG                 CHAR(1) DEFAULT 'N' CHECK (CDB_FLAG IN ('Y','N')),
    EXADATA_FLAG             CHAR(1) DEFAULT 'N' CHECK (EXADATA_FLAG IN ('Y','N')),

    PRIMARY_HOST_NAME        VARCHAR2(256),
    REGION_NAME              VARCHAR2(128),
    AVAILABILITY_DOMAIN      VARCHAR2(128),

    TAGS_JSON                JSON,
    CREATED_AT               TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT               TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT UK_AWR_SOURCE_SYSTEM_01
        UNIQUE (SOURCE_SYSTEM_CODE),

    CONSTRAINT UK_AWR_SOURCE_SYSTEM_02
        UNIQUE (DBID, DB_UNIQUE_NAME)
);

--------------------------------------------------------------------------------
-- 2. INGEST RUN AUDIT
--------------------------------------------------------------------------------
CREATE TABLE AWR_INGEST_RUN (
    INGEST_RUN_ID            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RUN_GUID                 VARCHAR2(64)        NOT NULL,
    PIPELINE_NAME            VARCHAR2(128)       NOT NULL,
    PIPELINE_VERSION         VARCHAR2(64),
    TRIGGER_TYPE             VARCHAR2(30),
    STATUS                   VARCHAR2(30)        NOT NULL,
    STARTED_AT               TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ENDED_AT                 TIMESTAMP(6),
    FILE_COUNT               NUMBER DEFAULT 0 NOT NULL,
    SUCCESS_COUNT            NUMBER DEFAULT 0 NOT NULL,
    ERROR_COUNT              NUMBER DEFAULT 0 NOT NULL,
    REQUESTED_BY             VARCHAR2(256),
    EXECUTION_HOST           VARCHAR2(256),
    NOTES                    VARCHAR2(4000),
    PARAMETERS_JSON          JSON,
    ERROR_JSON               JSON,

    CONSTRAINT UK_AWR_INGEST_RUN_01 UNIQUE (RUN_GUID),
    CONSTRAINT CK_AWR_INGEST_RUN_STATUS
        CHECK (STATUS IN ('STARTED','COMPLETED','COMPLETED_WITH_ERRORS','FAILED','CANCELLED'))
);

--------------------------------------------------------------------------------
-- 3. MASTER AWR REPORT TABLE
--------------------------------------------------------------------------------
CREATE TABLE AWR_REPORT (
    AWR_ID                   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SOURCE_SYSTEM_ID         NUMBER               NOT NULL,
    INGEST_RUN_ID            NUMBER,
    REPLAY_OF_AWR_ID         NUMBER,

    SOURCE_FILE_NAME         VARCHAR2(512)        NOT NULL,
    SOURCE_FILE_PATH         VARCHAR2(1024),
    OBJECT_STORE_URI         VARCHAR2(2048),
    FILE_HASH_SHA256         VARCHAR2(128)        NOT NULL,
    FILE_SIZE_BYTES          NUMBER,
    REPORT_FORMAT            VARCHAR2(30) DEFAULT 'AWR_OUT' NOT NULL,
    INGEST_MODE              VARCHAR2(30) DEFAULT 'NORMAL' NOT NULL,

    DB_NAME                  VARCHAR2(128),
    DBID                     NUMBER,
    INSTANCE_NAME            VARCHAR2(128),
    INSTANCE_NUMBER          NUMBER,
    HOST_NAME                VARCHAR2(256),
    PLATFORM_NAME            VARCHAR2(256),
    DB_VERSION               VARCHAR2(64),

    SNAP_ID_BEGIN            NUMBER,
    SNAP_ID_END              NUMBER,
    SNAP_TIME_BEGIN          TIMESTAMP(6),
    SNAP_TIME_END            TIMESTAMP(6),
    SNAP_ELAPSED_MINUTES     NUMBER(12,2),

    PARSE_STATUS             VARCHAR2(30) DEFAULT 'PARSED' NOT NULL,
    REPORT_CLASS             VARCHAR2(30),
    WORKLOAD_CLASS           VARCHAR2(50),
    ANOMALY_FLAG             CHAR(1) DEFAULT 'N' CHECK (ANOMALY_FLAG IN ('Y','N')),

    RAW_METADATA_JSON        JSON,
    RAW_HEADER_JSON          JSON,
    PARSER_OUTPUT_JSON       JSON,
    PARSER_WARNINGS_JSON     JSON,

    CREATED_AT               TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT               TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT FK_AWR_REPORT_SOURCE_SYSTEM
        FOREIGN KEY (SOURCE_SYSTEM_ID)
        REFERENCES AWR_SOURCE_SYSTEM (SOURCE_SYSTEM_ID),

    CONSTRAINT FK_AWR_REPORT_INGEST_RUN
        FOREIGN KEY (INGEST_RUN_ID)
        REFERENCES AWR_INGEST_RUN (INGEST_RUN_ID),

    CONSTRAINT FK_AWR_REPORT_REPLAY_OF
        FOREIGN KEY (REPLAY_OF_AWR_ID)
        REFERENCES AWR_REPORT (AWR_ID),

    CONSTRAINT CK_AWR_REPORT_PARSE_STATUS
        CHECK (PARSE_STATUS IN ('LOADED','PARSED','PARTIAL','FAILED','SKIPPED')),

    CONSTRAINT CK_AWR_REPORT_INGEST_MODE
        CHECK (INGEST_MODE IN ('NORMAL','REPLAY','TEST','BACKFILL'))
)
PARTITION BY RANGE (SNAP_TIME_END)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION P_AWR_REPORT_BOOTSTRAP
    VALUES LESS THAN (TIMESTAMP '2025-01-01 00:00:00')
);

--------------------------------------------------------------------------------
-- 4. AWR SECTION DOCUMENTS
--------------------------------------------------------------------------------
CREATE TABLE AWR_SECTION_DOC (
    SECTION_DOC_ID           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    AWR_ID                   NUMBER                NOT NULL,
    SOURCE_SYSTEM_ID         NUMBER                NOT NULL,

    SNAP_TIME_BEGIN          TIMESTAMP(6)         NOT NULL,
    SNAP_TIME_END            TIMESTAMP(6)         NOT NULL,

    SECTION_NAME             VARCHAR2(128)        NOT NULL,
    SECTION_GROUP            VARCHAR2(64),
    SECTION_SEQ              NUMBER DEFAULT 1     NOT NULL,

    PARSE_CONFIDENCE         NUMBER(5,2),
    ROW_COUNT_PARSED         NUMBER,
    HAS_ANOMALY              CHAR(1) DEFAULT 'N' CHECK (HAS_ANOMALY IN ('Y','N')),

    SECTION_TEXT_CLOB        CLOB,
    SECTION_JSON             JSON,
    SECTION_STATS_JSON       JSON,

    CREATED_AT               TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT FK_AWR_SECTION_DOC_AWR
        FOREIGN KEY (AWR_ID)
        REFERENCES AWR_REPORT (AWR_ID),

    CONSTRAINT FK_AWR_SECTION_DOC_SOURCE
        FOREIGN KEY (SOURCE_SYSTEM_ID)
        REFERENCES AWR_SOURCE_SYSTEM (SOURCE_SYSTEM_ID),

    CONSTRAINT UK_AWR_SECTION_DOC_01
        UNIQUE (AWR_ID, SECTION_NAME, SECTION_SEQ)
)
PARTITION BY RANGE (SNAP_TIME_END)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION P_AWR_SECTION_BOOTSTRAP
    VALUES LESS THAN (TIMESTAMP '2025-01-01 00:00:00')
);

--------------------------------------------------------------------------------
-- 5. METRIC FACT TABLE
--------------------------------------------------------------------------------
CREATE TABLE AWR_METRIC_FACT (
    METRIC_FACT_ID           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    AWR_ID                   NUMBER                NOT NULL,
    SOURCE_SYSTEM_ID         NUMBER                NOT NULL,

    SNAP_TIME_BEGIN          TIMESTAMP(6)         NOT NULL,
    SNAP_TIME_END            TIMESTAMP(6)         NOT NULL,

    METRIC_DOMAIN            VARCHAR2(64)         NOT NULL,
    METRIC_NAME              VARCHAR2(256)        NOT NULL,
    METRIC_SUBTYPE           VARCHAR2(128),
    DIMENSION_1              VARCHAR2(256),
    DIMENSION_2              VARCHAR2(256),
    DIMENSION_3              VARCHAR2(256),

    METRIC_VALUE_NUM         NUMBER(30,10),
    METRIC_VALUE_TXT         VARCHAR2(4000),
    UNIT_OF_MEASURE          VARCHAR2(64),
    VALUE_DIRECTION          VARCHAR2(10),

    BASELINE_VALUE_NUM       NUMBER(30,10),
    DELTA_VALUE_NUM          NUMBER(30,10),
    ZSCORE_VALUE             NUMBER(18,8),
    PERCENTILE_VALUE         NUMBER(9,4),

    METRIC_JSON              JSON,
    CREATED_AT               TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT FK_AWR_METRIC_FACT_AWR
        FOREIGN KEY (AWR_ID)
        REFERENCES AWR_REPORT (AWR_ID),

    CONSTRAINT FK_AWR_METRIC_FACT_SOURCE
        FOREIGN KEY (SOURCE_SYSTEM_ID)
        REFERENCES AWR_SOURCE_SYSTEM (SOURCE_SYSTEM_ID)
)
PARTITION BY RANGE (SNAP_TIME_END)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION P_AWR_METRIC_BOOTSTRAP
    VALUES LESS THAN (TIMESTAMP '2025-01-01 00:00:00')
);

--------------------------------------------------------------------------------
-- 6. TOP SQL FACT TABLE
--------------------------------------------------------------------------------
CREATE TABLE AWR_TOP_SQL_FACT (
    TOP_SQL_FACT_ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    AWR_ID                   NUMBER                NOT NULL,
    SOURCE_SYSTEM_ID         NUMBER                NOT NULL,

    SNAP_TIME_BEGIN          TIMESTAMP(6)         NOT NULL,
    SNAP_TIME_END            TIMESTAMP(6)         NOT NULL,

    SQL_ID                   VARCHAR2(13)         NOT NULL,
    PLAN_HASH_VALUE          NUMBER,
    MODULE_NAME              VARCHAR2(256),
    PARSING_SCHEMA_NAME      VARCHAR2(128),

    RANK_BY_ELAPSED          NUMBER,
    RANK_BY_CPU              NUMBER,
    RANK_BY_GETS             NUMBER,
    RANK_BY_READS            NUMBER,
    RANK_BY_EXECUTIONS       NUMBER,

    ELAPSED_TIME_SEC         NUMBER(20,6),
    CPU_TIME_SEC             NUMBER(20,6),
    IO_TIME_SEC              NUMBER(20,6),
    BUFFER_GETS              NUMBER(20,6),
    DISK_READS               NUMBER(20,6),
    EXECUTIONS               NUMBER(20,6),
    ROWS_PROCESSED           NUMBER(20,6),

    ELAPSED_PER_EXEC_SEC     NUMBER(20,6),
    CPU_PER_EXEC_SEC         NUMBER(20,6),
    GETS_PER_EXEC            NUMBER(20,6),
    READS_PER_EXEC           NUMBER(20,6),

    SQL_TEXT_SHORT           VARCHAR2(4000),
    SQL_TEXT_CLOB            CLOB,
    SQL_METRICS_JSON         JSON,

    CREATED_AT               TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT FK_AWR_TOP_SQL_FACT_AWR
        FOREIGN KEY (AWR_ID)
        REFERENCES AWR_REPORT (AWR_ID),

    CONSTRAINT FK_AWR_TOP_SQL_FACT_SOURCE
        FOREIGN KEY (SOURCE_SYSTEM_ID)
        REFERENCES AWR_SOURCE_SYSTEM (SOURCE_SYSTEM_ID)
)
PARTITION BY RANGE (SNAP_TIME_END)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION P_AWR_TOP_SQL_BOOTSTRAP
    VALUES LESS THAN (TIMESTAMP '2025-01-01 00:00:00')
);

--------------------------------------------------------------------------------
-- 7. WAIT EVENT FACT TABLE
--------------------------------------------------------------------------------
CREATE TABLE AWR_WAIT_EVENT_FACT (
    WAIT_EVENT_FACT_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    AWR_ID                   NUMBER                NOT NULL,
    SOURCE_SYSTEM_ID         NUMBER                NOT NULL,

    SNAP_TIME_BEGIN          TIMESTAMP(6)         NOT NULL,
    SNAP_TIME_END            TIMESTAMP(6)         NOT NULL,

    WAIT_CLASS               VARCHAR2(128)        NOT NULL,
    EVENT_NAME               VARCHAR2(256)        NOT NULL,

    TOTAL_WAITS              NUMBER(20,6),
    TOTAL_TIMEOUTS           NUMBER(20,6),
    TIME_WAITED_SEC          NUMBER(20,6),
    AVG_WAIT_MS              NUMBER(20,6),
    PCT_DB_TIME              NUMBER(9,4),

    RANK_IN_AWR              NUMBER,
    FOREGROUND_FLAG          CHAR(1) DEFAULT 'Y' CHECK (FOREGROUND_FLAG IN ('Y','N')),
    WAIT_METRICS_JSON        JSON,

    CREATED_AT               TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT FK_AWR_WAIT_EVENT_FACT_AWR
        FOREIGN KEY (AWR_ID)
        REFERENCES AWR_REPORT (AWR_ID),

    CONSTRAINT FK_AWR_WAIT_EVENT_FACT_SOURCE
        FOREIGN KEY (SOURCE_SYSTEM_ID)
        REFERENCES AWR_SOURCE_SYSTEM (SOURCE_SYSTEM_ID)
)
PARTITION BY RANGE (SNAP_TIME_END)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION P_AWR_WAIT_EVENT_BOOTSTRAP
    VALUES LESS THAN (TIMESTAMP '2025-01-01 00:00:00')
);

--------------------------------------------------------------------------------
-- 8. FEATURE VECTOR TABLE
--------------------------------------------------------------------------------
CREATE TABLE AWR_FEATURE_VECTOR (
    FEATURE_VECTOR_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    AWR_ID                   NUMBER                NOT NULL,
    SOURCE_SYSTEM_ID         NUMBER                NOT NULL,

    OBSERVED_AT              TIMESTAMP(6)         NOT NULL,
    VECTOR_VERSION           VARCHAR2(64)         NOT NULL,
    FEATURE_SET_NAME         VARCHAR2(128)        NOT NULL,
    FEATURE_SET_VERSION      VARCHAR2(64)         NOT NULL,

    WORKLOAD_CLASS           VARCHAR2(50),
    VECTOR_STATUS            VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL,

    FEATURE_VECTOR           VECTOR(256, FLOAT32),
    NARRATIVE_EMBEDDING      VECTOR(1536, FLOAT32),

    FEATURE_JSON             JSON,
    NORMALIZATION_JSON       JSON,
    EXPLANATION_JSON         JSON,
    SOURCE_LINEAGE_JSON      JSON,

    CREATED_AT               TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT FK_AWR_FEATURE_VECTOR_AWR
        FOREIGN KEY (AWR_ID)
        REFERENCES AWR_REPORT (AWR_ID),

    CONSTRAINT FK_AWR_FEATURE_VECTOR_SOURCE
        FOREIGN KEY (SOURCE_SYSTEM_ID)
        REFERENCES AWR_SOURCE_SYSTEM (SOURCE_SYSTEM_ID),

    CONSTRAINT UK_AWR_FEATURE_VECTOR_01
        UNIQUE (AWR_ID, FEATURE_SET_NAME, FEATURE_SET_VERSION)
)
PARTITION BY RANGE (OBSERVED_AT)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION P_AWR_FV_BOOTSTRAP
    VALUES LESS THAN (TIMESTAMP '2025-01-01 00:00:00')
);

--------------------------------------------------------------------------------
-- 9. SCORING MODEL DEFINITION
--------------------------------------------------------------------------------
CREATE TABLE AWR_SCORING_MODEL (
    SCORING_MODEL_ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MODEL_CODE               VARCHAR2(100)        NOT NULL,
    MODEL_NAME               VARCHAR2(256)        NOT NULL,
    MODEL_VERSION            VARCHAR2(64)         NOT NULL,
    MODEL_TYPE               VARCHAR2(50)         NOT NULL,
    TARGET_DECISION_DOMAIN   VARCHAR2(64)         NOT NULL,
    STATUS                   VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL,

    SCORE_MIN                NUMBER(18,6) DEFAULT 0 NOT NULL,
    SCORE_MAX                NUMBER(18,6) DEFAULT 100 NOT NULL,

    THRESHOLD_JSON           JSON,
    MODEL_CONFIG_JSON        JSON,
    TRAINING_METADATA_JSON   JSON,

    CREATED_AT               TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT               TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT UK_AWR_SCORING_MODEL_01
        UNIQUE (MODEL_CODE, MODEL_VERSION),

    CONSTRAINT CK_AWR_SCORING_MODEL_STATUS
        CHECK (STATUS IN ('DRAFT','ACTIVE','RETIRED','DISABLED'))
);

--------------------------------------------------------------------------------
-- 10. SCORING WEIGHTS
--------------------------------------------------------------------------------
CREATE TABLE AWR_SCORING_WEIGHT (
    SCORING_WEIGHT_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SCORING_MODEL_ID         NUMBER                NOT NULL,
    FEATURE_CODE             VARCHAR2(128)        NOT NULL,
    FEATURE_NAME             VARCHAR2(256),
    FEATURE_DOMAIN           VARCHAR2(64),
    FEATURE_PATH             VARCHAR2(512),
    WEIGHT_VALUE             NUMBER(18,8)         NOT NULL,
    NORMALIZATION_METHOD     VARCHAR2(64),
    TRANSFORM_METHOD         VARCHAR2(64),
    POLARITY                 VARCHAR2(20),
    ENABLED_FLAG             CHAR(1) DEFAULT 'Y' CHECK (ENABLED_FLAG IN ('Y','N')),
    NOTES                    VARCHAR2(4000),

    CREATED_AT               TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT FK_AWR_SCORING_WEIGHT_MODEL
        FOREIGN KEY (SCORING_MODEL_ID)
        REFERENCES AWR_SCORING_MODEL (SCORING_MODEL_ID),

    CONSTRAINT UK_AWR_SCORING_WEIGHT_01
        UNIQUE (SCORING_MODEL_ID, FEATURE_CODE)
);

--------------------------------------------------------------------------------
-- 11. SCORE RESULTS
--------------------------------------------------------------------------------
CREATE TABLE AWR_SCORE_RESULT (
    SCORE_RESULT_ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    AWR_ID                   NUMBER                NOT NULL,
    SOURCE_SYSTEM_ID         NUMBER                NOT NULL,
    FEATURE_VECTOR_ID        NUMBER,
    SCORING_MODEL_ID         NUMBER                NOT NULL,

    SCORED_AT                TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    DECISION_DOMAIN          VARCHAR2(64)         NOT NULL,
    RISK_LEVEL               VARCHAR2(30),

    TOTAL_SCORE              NUMBER(18,8)         NOT NULL,
    CONFIDENCE_SCORE         NUMBER(9,4),
    SEVERITY_SCORE           NUMBER(9,4),
    URGENCY_SCORE            NUMBER(9,4),
    BUSINESS_IMPACT_SCORE    NUMBER(9,4),

    EXPLANATION_JSON         JSON,
    CONTRIBUTION_JSON        JSON,
    SCORECARD_JSON           JSON,

    CREATED_AT               TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT FK_AWR_SCORE_RESULT_AWR
        FOREIGN KEY (AWR_ID)
        REFERENCES AWR_REPORT (AWR_ID),

    CONSTRAINT FK_AWR_SCORE_RESULT_SOURCE
        FOREIGN KEY (SOURCE_SYSTEM_ID)
        REFERENCES AWR_SOURCE_SYSTEM (SOURCE_SYSTEM_ID),

    CONSTRAINT FK_AWR_SCORE_RESULT_VECTOR
        FOREIGN KEY (FEATURE_VECTOR_ID)
        REFERENCES AWR_FEATURE_VECTOR (FEATURE_VECTOR_ID),

    CONSTRAINT FK_AWR_SCORE_RESULT_MODEL
        FOREIGN KEY (SCORING_MODEL_ID)
        REFERENCES AWR_SCORING_MODEL (SCORING_MODEL_ID),

    CONSTRAINT CK_AWR_SCORE_RESULT_RISK
        CHECK (RISK_LEVEL IN ('LOW','MEDIUM','HIGH','CRITICAL'))
)
PARTITION BY RANGE (SCORED_AT)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION P_AWR_SCORE_BOOTSTRAP
    VALUES LESS THAN (TIMESTAMP '2025-01-01 00:00:00')
);

--------------------------------------------------------------------------------
-- 12. RECOMMENDATIONS
--------------------------------------------------------------------------------
CREATE TABLE AWR_RECOMMENDATION (
    RECOMMENDATION_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    AWR_ID                   NUMBER                NOT NULL,
    SOURCE_SYSTEM_ID         NUMBER                NOT NULL,
    SCORE_RESULT_ID          NUMBER,

    RECOMMENDED_AT           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    RECOMMENDATION_TYPE      VARCHAR2(64)         NOT NULL,
    RECOMMENDATION_CLASS     VARCHAR2(64),
    PRIORITY_CODE            VARCHAR2(30),
    STATUS                   VARCHAR2(30) DEFAULT 'PROPOSED' NOT NULL,

    TITLE                    VARCHAR2(500)        NOT NULL,
    SUMMARY                  VARCHAR2(4000),
    RATIONALE_JSON           JSON,
    EVIDENCE_JSON            JSON,
    PARAMETERS_JSON          JSON,

    ESTIMATED_BENEFIT_JSON   JSON,
    ESTIMATED_COST_JSON      JSON,
    ESTIMATED_RISK_JSON      JSON,
    TARGET_STATE_JSON        JSON,

    CREATED_AT               TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT               TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT FK_AWR_RECOMMENDATION_AWR
        FOREIGN KEY (AWR_ID)
        REFERENCES AWR_REPORT (AWR_ID),

    CONSTRAINT FK_AWR_RECOMMENDATION_SOURCE
        FOREIGN KEY (SOURCE_SYSTEM_ID)
        REFERENCES AWR_SOURCE_SYSTEM (SOURCE_SYSTEM_ID),

    CONSTRAINT FK_AWR_RECOMMENDATION_SCORE
        FOREIGN KEY (SCORE_RESULT_ID)
        REFERENCES AWR_SCORE_RESULT (SCORE_RESULT_ID),

    CONSTRAINT CK_AWR_RECOMMENDATION_STATUS
        CHECK (STATUS IN ('PROPOSED','APPROVED','REJECTED','IMPLEMENTED','CLOSED'))
);

--------------------------------------------------------------------------------
-- 13. ACTIONS / IMPLEMENTATION TRACKING
--------------------------------------------------------------------------------
CREATE TABLE AWR_ACTION (
    ACTION_ID                NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RECOMMENDATION_ID        NUMBER                NOT NULL,
    SOURCE_SYSTEM_ID         NUMBER                NOT NULL,

    ACTION_TYPE              VARCHAR2(64)         NOT NULL,
    ACTION_STATUS            VARCHAR2(30) DEFAULT 'PLANNED' NOT NULL,
    IMPLEMENTED_BY           VARCHAR2(256),
    IMPLEMENTED_AT           TIMESTAMP(6),

    CHANGE_TICKET            VARCHAR2(128),
    APPROVAL_REFERENCE       VARCHAR2(128),
    BEFORE_STATE_JSON        JSON,
    AFTER_STATE_JSON         JSON,
    ACTION_DETAILS_JSON      JSON,

    CREATED_AT               TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT               TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT FK_AWR_ACTION_RECOMMENDATION
        FOREIGN KEY (RECOMMENDATION_ID)
        REFERENCES AWR_RECOMMENDATION (RECOMMENDATION_ID),

    CONSTRAINT FK_AWR_ACTION_SOURCE
        FOREIGN KEY (SOURCE_SYSTEM_ID)
        REFERENCES AWR_SOURCE_SYSTEM (SOURCE_SYSTEM_ID),

    CONSTRAINT CK_AWR_ACTION_STATUS
        CHECK (ACTION_STATUS IN ('PLANNED','IN_PROGRESS','COMPLETED','FAILED','ROLLED_BACK','CANCELLED'))
);

--------------------------------------------------------------------------------
-- 14. OUTCOMES / FEEDBACK / TRUE LABELS
--------------------------------------------------------------------------------
CREATE TABLE AWR_OUTCOME (
    OUTCOME_ID               NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ACTION_ID                NUMBER                NOT NULL,
    SOURCE_SYSTEM_ID         NUMBER                NOT NULL,
    BASELINE_AWR_ID          NUMBER,
    POST_AWR_ID              NUMBER,

    OBSERVED_AT              TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    OBSERVATION_WINDOW_HRS   NUMBER(12,2),

    OUTCOME_STATUS           VARCHAR2(30)         NOT NULL,
    SUCCESS_FLAG             CHAR(1) DEFAULT 'N' CHECK (SUCCESS_FLAG IN ('Y','N')),

    DELTA_CPU_PCT            NUMBER(18,8),
    DELTA_DB_TIME_PCT        NUMBER(18,8),
    DELTA_IO_PCT             NUMBER(18,8),
    DELTA_AAS_PCT            NUMBER(18,8),
    DELTA_THROUGHPUT_PCT     NUMBER(18,8),

    ACTUAL_BENEFIT_JSON      JSON,
    ACTUAL_COST_JSON         JSON,
    OUTCOME_METRICS_JSON     JSON,
    LABEL_JSON               JSON,
    REVIEW_NOTES             VARCHAR2(4000),

    CREATED_AT               TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT FK_AWR_OUTCOME_ACTION
        FOREIGN KEY (ACTION_ID)
        REFERENCES AWR_ACTION (ACTION_ID),

    CONSTRAINT FK_AWR_OUTCOME_SOURCE
        FOREIGN KEY (SOURCE_SYSTEM_ID)
        REFERENCES AWR_SOURCE_SYSTEM (SOURCE_SYSTEM_ID),

    CONSTRAINT FK_AWR_OUTCOME_BASE_AWR
        FOREIGN KEY (BASELINE_AWR_ID)
        REFERENCES AWR_REPORT (AWR_ID),

    CONSTRAINT FK_AWR_OUTCOME_POST_AWR
        FOREIGN KEY (POST_AWR_ID)
        REFERENCES AWR_REPORT (AWR_ID),

    CONSTRAINT CK_AWR_OUTCOME_STATUS
        CHECK (OUTCOME_STATUS IN ('IMPROVED','UNCHANGED','DEGRADED','MIXED'))
);

--------------------------------------------------------------------------------
-- 15. MODEL / INFERENCE AUDIT
--------------------------------------------------------------------------------
CREATE TABLE AWR_MODEL_RUN (
    MODEL_RUN_ID             NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SCORING_MODEL_ID         NUMBER,
    SOURCE_SYSTEM_ID         NUMBER,
    AWR_ID                   NUMBER,
    FEATURE_VECTOR_ID        NUMBER,

    RUN_TYPE                 VARCHAR2(30)         NOT NULL,
    RUN_STATUS               VARCHAR2(30)         NOT NULL,
    STARTED_AT               TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    ENDED_AT                 TIMESTAMP(6),

    TRAINING_SET_REF         VARCHAR2(256),
    MODEL_ARTIFACT_REF       VARCHAR2(2048),
    METRICS_JSON             JSON,
    PARAMS_JSON              JSON,
    OUTPUT_JSON              JSON,
    ERROR_JSON               JSON,

    CONSTRAINT FK_AWR_MODEL_RUN_MODEL
        FOREIGN KEY (SCORING_MODEL_ID)
        REFERENCES AWR_SCORING_MODEL (SCORING_MODEL_ID),

    CONSTRAINT FK_AWR_MODEL_RUN_SOURCE
        FOREIGN KEY (SOURCE_SYSTEM_ID)
        REFERENCES AWR_SOURCE_SYSTEM (SOURCE_SYSTEM_ID),

    CONSTRAINT FK_AWR_MODEL_RUN_AWR
        FOREIGN KEY (AWR_ID)
        REFERENCES AWR_REPORT (AWR_ID),

    CONSTRAINT FK_AWR_MODEL_RUN_VECTOR
        FOREIGN KEY (FEATURE_VECTOR_ID)
        REFERENCES AWR_FEATURE_VECTOR (FEATURE_VECTOR_ID),

    CONSTRAINT CK_AWR_MODEL_RUN_TYPE
        CHECK (RUN_TYPE IN ('TRAIN','SCORE','RETRAIN','BACKTEST')),

    CONSTRAINT CK_AWR_MODEL_RUN_STATUS
        CHECK (RUN_STATUS IN ('STARTED','COMPLETED','FAILED','CANCELLED'))
);

--------------------------------------------------------------------------------
-- 16. RELATIONAL INDEXES
--------------------------------------------------------------------------------
CREATE INDEX IX_AWR_SOURCE_SYSTEM_01
    ON AWR_SOURCE_SYSTEM (CUSTOMER_NAME, ENVIRONMENT_NAME, APPLICATION_NAME);

CREATE INDEX IX_AWR_INGEST_RUN_01
    ON AWR_INGEST_RUN (STATUS, STARTED_AT);

CREATE INDEX IX_AWR_REPORT_01
    ON AWR_REPORT (SOURCE_SYSTEM_ID, SNAP_TIME_END) LOCAL;

CREATE INDEX IX_AWR_REPORT_02
    ON AWR_REPORT (DBID, INSTANCE_NUMBER, SNAP_TIME_END) LOCAL;

CREATE INDEX IX_AWR_REPORT_03
    ON AWR_REPORT (PARSE_STATUS, SNAP_TIME_END) LOCAL;

CREATE INDEX IX_AWR_REPORT_04
    ON AWR_REPORT (ANOMALY_FLAG, SNAP_TIME_END) LOCAL;

CREATE INDEX IX_AWR_REPORT_05
    ON AWR_REPORT (SOURCE_FILE_NAME);

CREATE INDEX IX_AWR_REPORT_06
    ON AWR_REPORT (FILE_HASH_SHA256);

CREATE INDEX IX_AWR_REPORT_07
    ON AWR_REPORT (INGEST_MODE, SNAP_TIME_END) LOCAL;

CREATE INDEX IX_AWR_REPORT_08
    ON AWR_REPORT (REPLAY_OF_AWR_ID);

CREATE INDEX IX_AWR_SECTION_DOC_01
    ON AWR_SECTION_DOC (AWR_ID, SECTION_NAME);

CREATE INDEX IX_AWR_SECTION_DOC_02
    ON AWR_SECTION_DOC (SOURCE_SYSTEM_ID, SECTION_GROUP, SNAP_TIME_END) LOCAL;

CREATE INDEX IX_AWR_METRIC_FACT_01
    ON AWR_METRIC_FACT (SOURCE_SYSTEM_ID, METRIC_DOMAIN, METRIC_NAME, SNAP_TIME_END) LOCAL;

CREATE INDEX IX_AWR_METRIC_FACT_02
    ON AWR_METRIC_FACT (AWR_ID, METRIC_DOMAIN, METRIC_NAME);

CREATE INDEX IX_AWR_METRIC_FACT_03
    ON AWR_METRIC_FACT (DIMENSION_1, DIMENSION_2);

CREATE INDEX IX_AWR_TOP_SQL_FACT_01
    ON AWR_TOP_SQL_FACT (SOURCE_SYSTEM_ID, SQL_ID, SNAP_TIME_END) LOCAL;

CREATE INDEX IX_AWR_TOP_SQL_FACT_02
    ON AWR_TOP_SQL_FACT (AWR_ID, SQL_ID);

CREATE INDEX IX_AWR_TOP_SQL_FACT_03
    ON AWR_TOP_SQL_FACT (SQL_ID, PLAN_HASH_VALUE, SNAP_TIME_END) LOCAL;

CREATE INDEX IX_AWR_TOP_SQL_FACT_04
    ON AWR_TOP_SQL_FACT (SOURCE_SYSTEM_ID, RANK_BY_ELAPSED, SNAP_TIME_END) LOCAL;

CREATE INDEX IX_AWR_WAIT_EVENT_FACT_01
    ON AWR_WAIT_EVENT_FACT (SOURCE_SYSTEM_ID, WAIT_CLASS, SNAP_TIME_END) LOCAL;

CREATE INDEX IX_AWR_WAIT_EVENT_FACT_02
    ON AWR_WAIT_EVENT_FACT (SOURCE_SYSTEM_ID, EVENT_NAME, SNAP_TIME_END) LOCAL;

CREATE INDEX IX_AWR_WAIT_EVENT_FACT_03
    ON AWR_WAIT_EVENT_FACT (AWR_ID, WAIT_CLASS, EVENT_NAME);

CREATE INDEX IX_AWR_WAIT_EVENT_FACT_04
    ON AWR_WAIT_EVENT_FACT (SOURCE_SYSTEM_ID, RANK_IN_AWR, SNAP_TIME_END) LOCAL;

CREATE INDEX IX_AWR_FEATURE_VECTOR_01
    ON AWR_FEATURE_VECTOR (SOURCE_SYSTEM_ID, FEATURE_SET_NAME, OBSERVED_AT) LOCAL;

CREATE INDEX IX_AWR_FEATURE_VECTOR_02
    ON AWR_FEATURE_VECTOR (AWR_ID, FEATURE_SET_NAME, FEATURE_SET_VERSION);

CREATE INDEX IX_AWR_SCORING_MODEL_01
    ON AWR_SCORING_MODEL (STATUS, TARGET_DECISION_DOMAIN);

CREATE INDEX IX_AWR_SCORE_RESULT_01
    ON AWR_SCORE_RESULT (SOURCE_SYSTEM_ID, DECISION_DOMAIN, SCORED_AT) LOCAL;

CREATE INDEX IX_AWR_SCORE_RESULT_02
    ON AWR_SCORE_RESULT (AWR_ID, SCORING_MODEL_ID);

CREATE INDEX IX_AWR_SCORE_RESULT_03
    ON AWR_SCORE_RESULT (RISK_LEVEL, TOTAL_SCORE, SCORED_AT) LOCAL;

CREATE INDEX IX_AWR_RECOMMENDATION_01
    ON AWR_RECOMMENDATION (SOURCE_SYSTEM_ID, STATUS, RECOMMENDED_AT);

CREATE INDEX IX_AWR_RECOMMENDATION_02
    ON AWR_RECOMMENDATION (AWR_ID, RECOMMENDATION_TYPE);

CREATE INDEX IX_AWR_ACTION_01
    ON AWR_ACTION (RECOMMENDATION_ID, ACTION_STATUS);

CREATE INDEX IX_AWR_ACTION_02
    ON AWR_ACTION (SOURCE_SYSTEM_ID, ACTION_STATUS, IMPLEMENTED_AT);

CREATE INDEX IX_AWR_OUTCOME_01
    ON AWR_OUTCOME (ACTION_ID, OUTCOME_STATUS);

CREATE INDEX IX_AWR_OUTCOME_02
    ON AWR_OUTCOME (SOURCE_SYSTEM_ID, OBSERVED_AT);

CREATE INDEX IX_AWR_MODEL_RUN_01
    ON AWR_MODEL_RUN (RUN_TYPE, RUN_STATUS, STARTED_AT);

CREATE INDEX IX_AWR_MODEL_RUN_02
    ON AWR_MODEL_RUN (SCORING_MODEL_ID, STARTED_AT);

--------------------------------------------------------------------------------
-- 17. JSON FUNCTION-BASED INDEXES
--------------------------------------------------------------------------------
CREATE INDEX IX_AWR_REPORT_JSON_01
    ON AWR_REPORT (
        JSON_VALUE(RAW_METADATA_JSON, '$.release' RETURNING VARCHAR2(64))
    );

CREATE INDEX IX_AWR_REPORT_JSON_02
    ON AWR_REPORT (
        JSON_VALUE(RAW_METADATA_JSON, '$.startup_time' RETURNING VARCHAR2(64))
    );

CREATE INDEX IX_AWR_SECTION_DOC_JSON_01
    ON AWR_SECTION_DOC (
        JSON_VALUE(SECTION_STATS_JSON, '$.top_wait_event' RETURNING VARCHAR2(256))
    );

CREATE INDEX IX_AWR_SCORE_RESULT_JSON_01
    ON AWR_SCORE_RESULT (
        JSON_VALUE(SCORECARD_JSON, '$.primary_bottleneck' RETURNING VARCHAR2(128))
    );

--------------------------------------------------------------------------------
-- 18. JSON SEARCH INDEXES
--------------------------------------------------------------------------------
CREATE SEARCH INDEX SI_AWR_REPORT_JSON
    ON AWR_REPORT (PARSER_OUTPUT_JSON)
    FOR JSON;

CREATE SEARCH INDEX SI_AWR_SECTION_DOC_JSON
    ON AWR_SECTION_DOC (SECTION_JSON)
    FOR JSON;

--------------------------------------------------------------------------------
-- 19. VECTOR INDEXES
--------------------------------------------------------------------------------
CREATE VECTOR INDEX VIDX_AWR_FEATURE_VECTOR_HNSW
    ON AWR_FEATURE_VECTOR (FEATURE_VECTOR)
    ORGANIZATION INMEMORY NEIGHBOR GRAPH
    DISTANCE COSINE
    WITH TARGET ACCURACY 95;

CREATE VECTOR INDEX VIDX_AWR_NARRATIVE_EMBED_HNSW
    ON AWR_FEATURE_VECTOR (NARRATIVE_EMBEDDING)
    ORGANIZATION INMEMORY NEIGHBOR GRAPH
    DISTANCE COSINE
    WITH TARGET ACCURACY 95;

--------------------------------------------------------------------------------
-- 20. HELPFUL VIEWS
--------------------------------------------------------------------------------
CREATE OR REPLACE VIEW VW_AWR_REPORT_LATEST AS
SELECT
    s.SOURCE_SYSTEM_CODE,
    s.CUSTOMER_NAME,
    s.ENVIRONMENT_NAME,
    r.AWR_ID,
    r.DB_NAME,
    r.DBID,
    r.INSTANCE_NAME,
    r.INSTANCE_NUMBER,
    r.SNAP_ID_BEGIN,
    r.SNAP_ID_END,
    r.SNAP_TIME_BEGIN,
    r.SNAP_TIME_END,
    r.SNAP_ELAPSED_MINUTES,
    r.PARSE_STATUS,
    r.ANOMALY_FLAG,
    r.INGEST_MODE,
    r.SOURCE_FILE_NAME,
    r.CREATED_AT
FROM AWR_REPORT r
JOIN AWR_SOURCE_SYSTEM s
  ON s.SOURCE_SYSTEM_ID = r.SOURCE_SYSTEM_ID
WHERE r.SNAP_TIME_END = (
    SELECT MAX(r2.SNAP_TIME_END)
    FROM AWR_REPORT r2
    WHERE r2.SOURCE_SYSTEM_ID = r.SOURCE_SYSTEM_ID
);

CREATE OR REPLACE VIEW VW_AWR_RECOMMENDATION_CYCLE AS
SELECT
    s.SOURCE_SYSTEM_CODE,
    r.AWR_ID,
    r.SNAP_TIME_END,
    sr.SCORE_RESULT_ID,
    sr.DECISION_DOMAIN,
    sr.TOTAL_SCORE,
    sr.RISK_LEVEL,
    rec.RECOMMENDATION_ID,
    rec.RECOMMENDATION_TYPE,
    rec.STATUS AS RECOMMENDATION_STATUS,
    act.ACTION_ID,
    act.ACTION_TYPE,
    act.ACTION_STATUS,
    o.OUTCOME_ID,
    o.OUTCOME_STATUS,
    o.SUCCESS_FLAG
FROM AWR_REPORT r
JOIN AWR_SOURCE_SYSTEM s
  ON s.SOURCE_SYSTEM_ID = r.SOURCE_SYSTEM_ID
LEFT JOIN AWR_SCORE_RESULT sr
  ON sr.AWR_ID = r.AWR_ID
LEFT JOIN AWR_RECOMMENDATION rec
  ON rec.SCORE_RESULT_ID = sr.SCORE_RESULT_ID
LEFT JOIN AWR_ACTION act
  ON act.RECOMMENDATION_ID = rec.RECOMMENDATION_ID
LEFT JOIN AWR_OUTCOME o
  ON o.ACTION_ID = act.ACTION_ID;

CREATE OR REPLACE VIEW VW_AWR_TOP_SQL_TREND AS
SELECT
    s.SOURCE_SYSTEM_CODE,
    t.SOURCE_SYSTEM_ID,
    t.AWR_ID,
    t.SNAP_TIME_BEGIN,
    t.SNAP_TIME_END,
    t.SQL_ID,
    t.PLAN_HASH_VALUE,
    t.RANK_BY_ELAPSED,
    t.RANK_BY_CPU,
    t.ELAPSED_TIME_SEC,
    t.CPU_TIME_SEC,
    t.IO_TIME_SEC,
    t.EXECUTIONS,
    t.ELAPSED_PER_EXEC_SEC,
    t.CPU_PER_EXEC_SEC
FROM AWR_TOP_SQL_FACT t
JOIN AWR_SOURCE_SYSTEM s
  ON s.SOURCE_SYSTEM_ID = t.SOURCE_SYSTEM_ID;

CREATE OR REPLACE VIEW VW_AWR_WAIT_EVENT_TREND AS
SELECT
    s.SOURCE_SYSTEM_CODE,
    w.SOURCE_SYSTEM_ID,
    w.AWR_ID,
    w.SNAP_TIME_BEGIN,
    w.SNAP_TIME_END,
    w.WAIT_CLASS,
    w.EVENT_NAME,
    w.RANK_IN_AWR,
    w.TOTAL_WAITS,
    w.TIME_WAITED_SEC,
    w.AVG_WAIT_MS,
    w.PCT_DB_TIME
FROM AWR_WAIT_EVENT_FACT w
JOIN AWR_SOURCE_SYSTEM s
  ON s.SOURCE_SYSTEM_ID = w.SOURCE_SYSTEM_ID;

--------------------------------------------------------------------------------
-- 21. SEED EXAMPLE: DEFAULT WEIGHTED MODEL
--------------------------------------------------------------------------------
INSERT INTO AWR_SCORING_MODEL (
    MODEL_CODE,
    MODEL_NAME,
    MODEL_VERSION,
    MODEL_TYPE,
    TARGET_DECISION_DOMAIN,
    STATUS,
    THRESHOLD_JSON,
    MODEL_CONFIG_JSON
) VALUES (
    'AWR_WEIGHTED_CORE',
    'AWR Weighted Core Scoring Model',
    '1.0.0',
    'WEIGHTED',
    'SIZING',
    'ACTIVE',
    JSON('{"low":25,"medium":50,"high":75,"critical":90}'),
    JSON('{"feature_set":"CORE_256","notes":"Initial weighted scoring model for demo"}')
);

INSERT INTO AWR_SCORING_WEIGHT (
    SCORING_MODEL_ID, FEATURE_CODE, FEATURE_NAME, FEATURE_DOMAIN, FEATURE_PATH,
    WEIGHT_VALUE, NORMALIZATION_METHOD, TRANSFORM_METHOD, POLARITY
)
SELECT
    m.SCORING_MODEL_ID,
    'CPU_UTIL_P95',
    'CPU Utilization P95',
    'CPU',
    '$.CPU_UTIL_P95',
    0.20,
    'MINMAX',
    'NONE',
    'HIGH_BAD'
FROM AWR_SCORING_MODEL m
WHERE m.MODEL_CODE = 'AWR_WEIGHTED_CORE'
  AND m.MODEL_VERSION = '1.0.0';

INSERT INTO AWR_SCORING_WEIGHT (
    SCORING_MODEL_ID, FEATURE_CODE, FEATURE_NAME, FEATURE_DOMAIN, FEATURE_PATH,
    WEIGHT_VALUE, NORMALIZATION_METHOD, TRANSFORM_METHOD, POLARITY
)
SELECT
    m.SCORING_MODEL_ID,
    'DB_TIME_PER_TXN',
    'DB Time Per Transaction',
    'LOAD',
    '$.DB_TIME_PER_TXN',
    0.20,
    'ROBUST',
    'LOG1P',
    'HIGH_BAD'
FROM AWR_SCORING_MODEL m
WHERE m.MODEL_CODE = 'AWR_WEIGHTED_CORE'
  AND m.MODEL_VERSION = '1.0.0';

INSERT INTO AWR_SCORING_WEIGHT (
    SCORING_MODEL_ID, FEATURE_CODE, FEATURE_NAME, FEATURE_DOMAIN, FEATURE_PATH,
    WEIGHT_VALUE, NORMALIZATION_METHOD, TRANSFORM_METHOD, POLARITY
)
SELECT
    m.SCORING_MODEL_ID,
    'READ_LATENCY_MS',
    'Read Latency (ms)',
    'IO',
    '$.READ_LATENCY_MS',
    0.15,
    'MINMAX',
    'NONE',
    'HIGH_BAD'
FROM AWR_SCORING_MODEL m
WHERE m.MODEL_CODE = 'AWR_WEIGHTED_CORE'
  AND m.MODEL_VERSION = '1.0.0';

INSERT INTO AWR_SCORING_WEIGHT (
    SCORING_MODEL_ID, FEATURE_CODE, FEATURE_NAME, FEATURE_DOMAIN, FEATURE_PATH,
    WEIGHT_VALUE, NORMALIZATION_METHOD, TRANSFORM_METHOD, POLARITY
)
SELECT
    m.SCORING_MODEL_ID,
    'LOG_FILE_SYNC_MS',
    'Log File Sync (ms)',
    'WAIT',
    '$.LOG_FILE_SYNC_MS',
    0.15,
    'MINMAX',
    'NONE',
    'HIGH_BAD'
FROM AWR_SCORING_MODEL m
WHERE m.MODEL_CODE = 'AWR_WEIGHTED_CORE'
  AND m.MODEL_VERSION = '1.0.0';

INSERT INTO AWR_SCORING_WEIGHT (
    SCORING_MODEL_ID, FEATURE_CODE, FEATURE_NAME, FEATURE_DOMAIN, FEATURE_PATH,
    WEIGHT_VALUE, NORMALIZATION_METHOD, TRANSFORM_METHOD, POLARITY
)
SELECT
    m.SCORING_MODEL_ID,
    'TOP_SQL_LOAD_CONCENTRATION',
    'Top SQL Load Concentration',
    'SQL',
    '$.TOP_SQL_LOAD_CONCENTRATION',
    0.15,
    'MINMAX',
    'NONE',
    'HIGH_BAD'
FROM AWR_SCORING_MODEL m
WHERE m.MODEL_CODE = 'AWR_WEIGHTED_CORE'
  AND m.MODEL_VERSION = '1.0.0';

INSERT INTO AWR_SCORING_WEIGHT (
    SCORING_MODEL_ID, FEATURE_CODE, FEATURE_NAME, FEATURE_DOMAIN, FEATURE_PATH,
    WEIGHT_VALUE, NORMALIZATION_METHOD, TRANSFORM_METHOD, POLARITY
)
SELECT
    m.SCORING_MODEL_ID,
    'AAS_PER_CPU',
    'Average Active Sessions per CPU',
    'CONCURRENCY',
    '$.AAS_PER_CPU',
    0.15,
    'MINMAX',
    'NONE',
    'HIGH_BAD'
FROM AWR_SCORING_MODEL m
WHERE m.MODEL_CODE = 'AWR_WEIGHTED_CORE'
  AND m.MODEL_VERSION = '1.0.0';

COMMIT;
